"""empty message

Revision ID: 1f9823662fbd
Revises: 9939f0631f7d
Create Date: 2020-09-17 18:26:29.109772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9823662fbd'
down_revision = '9939f0631f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'created_on',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'created_on',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
