"""empty message

Revision ID: 67e8d6a80a4b
Revises: ffe03f86d607
Create Date: 2020-09-17 18:17:04.135622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e8d6a80a4b'
down_revision = 'ffe03f86d607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'creation_date')
    op.drop_column('project', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_on', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('creation_date', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
