"""empty message

Revision ID: 9939f0631f7d
Revises: 67e8d6a80a4b
Create Date: 2020-09-17 18:25:17.791336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9939f0631f7d'
down_revision = '67e8d6a80a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_on', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
