"""empty message

Revision ID: ffe03f86d607
Revises: b7d576ac5a09
Create Date: 2020-09-17 18:11:00.134983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe03f86d607'
down_revision = 'b7d576ac5a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_on', sa.Date(), nullable=True))
    op.drop_column('project', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('creation_date', sa.DATETIME(), nullable=False))
    op.drop_column('project', 'created_on')
    # ### end Alembic commands ###
